name: Lint
on: pull_request
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v5.4.3
